// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  experimental: {
    externalTables: true,
  },

  migrations: {
    path: "prisma/migrations",
    initShadowDb: `
      CREATE EXTENSION IF NOT EXISTS postgis;
    `,
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
